run:
  timeout: 5m

linters:
  enable:
    - bodyclose
    - gosec
    - misspell

issues:
  exclude-dirs:
    - internal/delivery/grpc/orderv1

  exclude-rules:
    - path: internal/delivery/grpc/server.go
      linters:
        - gosec
      text: "G115"