version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - gosec
    - misspell
  exclusions:
    paths:
      - internal/delivery/grpc/orderv1
    rules:
      - path: internal/delivery/grpc/server.go
        linters:
          - gosec
        text: "G115"

formatters:
  enable:
    - gofmt
    - goimports
